<a href="https://colab.research.google.com/github/varasrisiri/Machine-Learning-Course_Part-1/blob/main/3.7_Handling_Imbalanced_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Imbalanced Dataset

A dataset with an unequal class distribution

In [4]:
#importing the dependencies
import numpy as np
import pandas as pd

In [6]:
credit_card_data = pd.read_csv('/content/credit_data.csv')

In [7]:
credit_card_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0

In [8]:
credit_card_data.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
213964,139469.0,-0.313355,1.038943,-0.093972,-0.540988,0.042780,-1.106101,0.603947,0.287733,-0.100080,...,-0.217842,-0.621741,0.153701,-0.042585,-0.503706,0.148254,0.118168,0.032668,9.12,0.0
213965,139469.0,2.030213,0.285221,-1.938915,1.027250,0.851942,-0.701464,0.615953,-0.241818,-0.349579,...,0.167846,0.510669,0.027440,0.689138,0.427077,-0.532637,-0.040637,-0.068185,2.90,0.0
213966,139470.0,0.142229,0.672251,0.983900,-0.293528,0.068882,-0.487888,0.491696,-0.118390,0.318579,...,0.000967,0.224127,0.213429,-0.107864,-1.475182,-0.749164,0.330808,0.289856,8.57,0.0
213967,139471.0,2.144033,-1.953243,-0.578686,-1.849212,-1.376208,0.807803,-1.911412,0.306645,-0.726623,...,-0.124630,-0.092680,0.193302,-0.404247,-0.484276,-0.247000,0.034838,-0.033122,84.00,0.0
213968,139471.0,2.157143,-0.687990,-2.032580,-0.940456,-0.215889,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
#determine the distribution of two classes
credit_card_data['Class'].value_counts()

Class
0.0    213570
1.0       398
Name: count, dtype: int64

0 --> legit Transactions - there's almost 99% of data

1 --> fradulent transaction - there's only 1% or less than 1% of data


This is higly imbalanced dataset --> because of most of the transactions is on one side

In [10]:
#separating the legit and fradulent transactions
legit = credit_card_data[credit_card_data.Class == 0]
fraud = credit_card_data[credit_card_data.Class == 1]

In [11]:
print(legit.shape)
print(fraud.shape)

(213570, 31)
(398, 31)

Under- sampling

    Build a sample dataset containing similar distribution o flegit and fradulent transaction

Number of Fraudulent Transaction --> 492

In [19]:
legit_sample = legit.sample(n=len(fraud))

In [20]:
print(legit_sample.shape)

(398, 31)

Concatenate the Two DataFrames

In [21]:
new_dataset = pd.concat([legit_sample, fraud], axis = 0)

In [22]:
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
72213,54615.0,-10.090735,-8.427415,0.570108,0.182253,0.763463,0.823147,2.781382,-3.301631,3.324253,...,-2.545084,1.191241,0.544622,-0.041950,0.917968,-0.610640,-5.902336,6.711628,173.71,0.0
119209,75371.0,-1.752440,1.103549,-0.670811,-1.264753,2.179360,3.283831,0.014581,1.054267,0.123683,...,-0.421451,-0.894908,0.020845,0.983826,0.033586,-0.005326,-0.452689,-0.661363,9.99,0.0
99701,67244.0,1.257719,0.364739,0.306923,0.690638,-0.357792,-1.067481,0.094272,-0.210300,0.014455,...,-0.286856,-0.820658,0.127663,0.343128,0.221120,0.094391,-0.022189,0.030944,1.29,0.0
212912,139039.0,-0.711190,0.439833,0.963645,-1.558006,-0.849632,0.856514,-2.359232,-4.103076,-1.221692,...,0.526395,0.555138,-0.715453,-0.339993,1.481497,0.221045,0.134007,0.163621,49.90,0.0
117504,74697.0,1.180944,0.174917,1.236852,1.241977,-0.809434,-0.364264,-0.460610,-0.012979,0.348159,...,0.107851,0.405480,-0.025042,0.356481,0.383385,-0.359036,0.069332,0.042060,5.79,0.0

In [23]:
new_dataset.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
208651,137211.0,0.630579,1.183631,-5.066283,2.179903,-0.703376,-0.103614,-3.490350,1.094734,-0.717418,...,0.621622,0.043807,0.102711,-0.601505,0.127371,-0.163009,0.853792,0.356503,39.45,1.0
212516,138894.0,-1.298443,1.948100,-4.509947,1.305805,-0.019486,-0.509238,-2.643398,1.283545,-2.515356,...,1.178032,1.360989,-0.272013,-0.325948,0.290703,0.841295,0.643094,0.201156,0.01,1.0
212644,138942.0,-2.356348,1.746360,-6.374624,1.772205,-3.439294,1.457811,-0.362577,1.443791,-1.927359,...,0.857942,0.621203,0.964817,-0.619437,-1.732613,0.108361,1.130828,0.415703,727.91,1.0
213092,139107.0,-4.666500,-3.952320,0.206094,5.153525,5.229469,0.939040,-0.635033,-0.704506,-0.234786,...,-0.664263,1.821422,0.113563,-0.759673,-0.502304,0.630639,-0.513880,0.729526,22.47,1.0
213116,139117.0,-3.975939,-1.244939,-3.707414,4.544772,4.050676,-3.407679,-5.063118,1.007042,-3.190158,...,1.059737,-0.037395,0.348707,-0.162929,0.410531,-0.123612,0.877424,0.667568,8.30,1.0

In [24]:
new_dataset['Class'].value_counts()

Class
0.0    398
1.0    398
Name: count, dtype: int64